name: "EC2 deploy with Terraform"
on:
  push:
    branches:
      - main 
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  plan:
    name: Terraform deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout (bring code to this VM)"
        uses: actions/checkout@v3
      
      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Setup AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: "Terraform deploy EC2"
        run:  |
          cd terraform
          terraform init
          terraform apply -var="EC2_PUBLIC_KEY=${EC2_PUBLIC_KEY}" -auto-approve
          EC2_PUBLIC_IP=$(terraform output -raw deployed_public_ip)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
        env:
          EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }} 

      - name: Setup SSH key
        run: |
          echo "$EC2_PRIVATE_KEY" > private.key
          sudo chmod 600 private.key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_SECRET_KEY }}

      - name: "Waiting 30s for EC2 to finish startup"
        run: |
          sleep 30s

      - name: "Copy project and run"
        run: |
          scp -o StrictHostKeyChecking=no -i private.key ./http.js ubuntu@${EC2_PUBLIC_IP}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no -i private.key ubuntu@${EC2_PUBLIC_IP} [[ ! -z $(ps | grep "node") ]] && killall node
          ssh -o StrictHostKeyChecking=no -i private.key ubuntu@${EC2_PUBLIC_IP} node http.js &
