name: "EC2 deploy with Terraform"
on:
  push:
    branches:
      - main 
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  plan:
    name: Terraform deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout (bring code to this VM)"
        uses: actions/checkout@v3
      
      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Setup AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: "Terraform deploy"
        run:  |
          cd terraform
          terraform init
          terraform plan
          terraform apply -auto-approve
          public_ip=$(terraform output deployed_public_ip)

      - name: "Print public IP"
        run: |
          echo $public_ip
