name: "EC2 deploy with Terraform"
on:
  push:
    branches:
      - main 
    paths:
      - '**.js'
      - 'terraform/**.tf'

jobs:
  deploy:
    name: App deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout (bring code to this VM)"
        uses: actions/checkout@v3
      
      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Setup AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: "Terraform deploy EC2"
        run:  |
          cd terraform
          terraform init
          terraform apply -var="EC2_PUBLIC_KEY=${EC2_PUBLIC_KEY}" -auto-approve
        env:
          EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}