name: "EC2 deploy with Terraform"
on:
  push:
    branches:
      - main 
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

env:
  HELLO_WORLD: "Hello world"

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout (bring code to this VM)"
        uses: actions/checkout@v3
      
      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform deploy"
        run:  |
          cd terraform
          terraform init
          terraform plan
